name: stats_api
description: A Dart package for the Covid Stats API.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  connectivity_plus: ^1.0.6
  equatable: ^2.0.3
  hive: ^2.0.4
  http: ^0.13.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.0.6
  hive_generator: ^1.1.0
  very_good_analysis: ^2.1.0
