name: covid19_api
description: A Dart API Client for the unofficial Covid-19 stats API.
version: 1.0.0
environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  equatable: ^2.0.3
  http: ^0.13.3
  json_annotation: ^4.0.1

dev_dependencies:
  build_runner: ^2.0.5
  coverage: ^1.0.3
  json_serializable: ^4.1.3
  meta: ^1.4.0
  mocktail: ^0.1.4
  very_good_analysis: ^2.1.2
  test: ^1.16.0
