name: local_storage
description: A Dart package for the local storage domain.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  hive: ^2.0.4
  stats_api:
    path: ../stats_api

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^2.1.0
